Ade reviews views+controller+routes
Fedakope/taffon pull request #13
Opened 2019-02-26 18:14 UTC by AlexisDew

## Reviews (routes, controller, views) : 

### At the end reviews only need : 
- [x] one method : `create`
- [x] one partial view : `_new.html.erb`

### Involve changes: 
- [x] Add an user `:show` route
- [x] Add a review `:create`nested route in the previous route
- [x] Remove `apply_id` field on the Review model with a new migration
- [x] Fix `has_many` relations on the Review model

2019-02-26 19:31 UTC, Aythabet commented on app/controllers/reviews_controller.rb
> +    @review.save ? (redirect_to root) : (render user_path(@user))
why redirect to root?
maybe redirect to: user who receives the review profile page?

2019-02-26 19:31 UTC, Aythabet requested changes
check the redirect in the change method for the reviews controller.

2019-02-27 09:10 UTC, AlexisDew commented on app/controllers/reviews_controller.rb
> +    @review.save ? (redirect_to root) : (render user_path(@user))
```suggestion
    @review.save
    redirect_to user_path(@user)
```

2019-02-27 09:19 UTC, Aythabet approved these changes

2019-02-27 09:20 UTC, merged